hostname: k3os01

ssh_authorized_keys:
  - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDKNicBhFRDwelNhyVrkitVENhvOXUpwSx7qfvd8cSKBxW1jNBbjJHm8eh59ViiB1RDQadGXoLd1tjIV9NS+yh8bTQ1XkLwwe9xsaYbidWQIiOGrW8RxkBmt8Yi+R/jtCEeF/NOHdhdYd3jL0BAJmRz3QmdTMRoE4IQjDwae8Lxe/B65RqsM9BaiDjzcpOqpezlt0s3M0BvgBQsTrqgUOw+ZSzVFLzNMzuhUrezgPH3WDhZ16ZH2B9eQWeOcW7Y48kFvGA8sNCtYVDyhy+9E3Tn6tvXPfP6JUqK1nUGUOoF1cV432dIP0oYpHqTS3hTDE7a5QQjouVEOWGC8AwuyGCR"

k3os:
  dns_nameservers:
  - 208.67.222.222
  - 208.67.220.220
  ntp_servers:
  - 0.us.pool.ntp.org
  - 1.us.pool.ntp.org
